### ISSUE TITLE
Plug-n-Play color config file(s)

### ISSUE THREAD

**Issue by diego-codes** [IBM-Design/spongy#8]
Currently the chrome plug-in only works with IBM Design colors. The extension should be brand agnostic and allow the user to upload a color palette config file.

# Tasks
- [ ] Allow extension to receive JSON, ASE,  and CSV files to configure brand color palettes.
- [ ] Store user color palettes to be persistent across browsing sessions.
- [ ] Create interface for user to upload palette files.
- [ ] Report to user if any errors occur during the processing of the palette files.

# Tests
- [ ] Upload a palette file that is not formatted properly and receive an error.
- [ ] Upload and process an accepted palette.
- [ ] Color matching works properly based on saved palette files.

**Comment by hollyos** [comment]
This should be an Epic, break this out into individual issues. Can re-open the above or just open new issues. A good rule of thumb is that a single issue shouldn’t take more than a sprint to complete. This issue would likely take a couple.

**Comment by seejamescode** [comment]
I'm working on a node module right now that will generate the right json format needed. Would we still need the ASE and CSV ones?

**Comment by diego-codes** [comment]
The module would generate the json file from what exactly?

**Comment by seejamescode** [comment]
Would take [this input](https://github.com/IBM-Design/colors/blob/master/source/colors.js) and export [this file](https://github.com/IBM-Design/colors/blob/master/ibm-colors.json).
